# Schema for the theme setting configuration file of the CANADA Bootstrap theme.

canada_experiments.settings:
  type: theme_settings
  label: 'Canada Experiments settings'
  mapping:
    cdn_provider:
      type: string
      label: 'CDN Provider'
    breadcrumb_home:
      type: integer
      label: 'Breadcrumb Home'
